[package]
name = "prjunnamed-pattern"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
prjunnamed-netlist.workspace = true

[features]
trace = []
